#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__) + '/../environment')

opts = {}
opts[:in_threads] = 0 if ARGV[0] == 'serial'

Labmapper::HostPoller.poll(opts)
Labmapper::HostPoller.serialize('../socket.json')
