#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__) + '/../environment')

# TODO this is horrible
version = `git describe`
version = $?.success? ? version.strip : ''

cmdopts = Trollop::options do
  version "Labmapper#poller #{version} (c) 2012 TJ Koblentz"
  opt :serial, "SSH hosts one after the other", default: false, short: '-s'
  opt :threads, "Use threads to parallelize", type: :int, short: '-t'
  opt :processes, "Use processes to parallelize", type: :int, short: '-p'
end

if (cmdopts[:threads] || cmdopts[:processes]) && cmdopts[:serial]
  Trollop::die :serial, "must not be set if threads/processes specified"
end

opts = {}

if cmdopts[:serial]
  opts[:in_theads] = opts[:in_processes] = 0
elsif cmdopts[:threads] || cmdopts[:processes]
  opts[:in_threads] = cmdopts[:threads]
  opts[:in_processes] = cmdopts[:processes]
else
  opts[:in_processes] = Labmapper::Config.hosts.size
end

Labmapper::HostPoller.poll(opts)
Labmapper::HostPoller.serialize('../socket.json')
